apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}
spec:
  selector:
    app: {{ .Values.frontend.name }}
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: http
